refactor(hook)!: :recycle:  hook is faster s/ half the lines
use less functions, make use of guard clauses to avoid various operations, better variables, improved messages, smaller form factor

by default user input is not requested, uncomment proceed to re-gain user input

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,122 +1,88 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+source "$(dirname "$0")/_/husky.sh"
 
-# vars
-OVERWRITE="\e[1A\e[K"
-INFO=" \033[1;34m\033[0m "
-DONE=" \033[0;32m\033[0m "
-ERROR=" \033[0;31m\033[0m "
-WARNING=" \033[1;33m\033[0m "
-ADD=" \033[0;34m\033[0m "
-COMMIT=" \033[1;35m\033[0m "
+# require user input to proceed with script or throw error (cmd not executable)
+function proceed() {
+    exec </dev/tty # open STDIN
 
-# request user input to decide whether to push or not
-get_input() {
-    exec </dev/tty # open STDIN to read input
-
-    # read user input
+    # read input
     while true; do
-        # `read -p` doesn't support standard formatting. Use `$'...'` instead
-        read -p $' \033[1;36m\033[0m  Do you wish to commit and push automagically? (Y/n) ' yn
+        #? TODO maybe change to a more generic question eg. "Continue?"
+        read -p $' \033[1;36m\033[0m  Continue? [Y/n] ' answer
 
-        # accept blank input as "yes"
-        if [ "$yn" = "" ]; then
-            yn="Y"
+        # accept blank as "y"
+        if [ "$answer" = "" ]; then
+            answer="y"
         fi
 
-        # check input
-        case "$yn" in
+        # it's either yes or no
+        case $answer in
         [Yy])
             return 0
             ;;
         [Nn])
-            return 1
+            exit 126
             ;;
-        *)
-            printf "Please answer with \"Y\" or \"N\"."
-            ;;
+        *) ;; # loop again
         esac
     done
-
     exec <&- # close STDIN
 }
 
-# check if user wants to track and commit changes automatically, then
-# either exits (1) or commits (0)
-function commit() {
-    to_track=$(get_input)
-    directory=$1
+# check if any files in ./.vscode/ have been modified in any way, if so call
+# proceed() and continue or exit
+function check_vscode() {
+    printf "\n$info Checking for changes in $code./.vscode/*$clr\n"
 
-    # Exiting is kind of an exception, so we check for it first
-    if [ $to_track -eq 1 ]; then
-        printf "${ERROR} Exiting\n"
-        return 1
-    fi
-
-    # it's assumed that the user wants to commit and push automatically
-    printf "${ADD} Tracking changes...\n" &&
-        git add ./$directory
-
-    printf "${COMMIT} Committing changes\n" &&
-        git commit -m "feat($directory): :robot:  update \`./$directory\`"
-    return
-}
-
-# given a directory/file it will check if it has been modified since the last
-# commit. If it has, it will invoke commit()
-function diff() {
-    directory="\e[1;34;1;40m./$1\e[0m"
-
-    printf "\n${INFO} Checking for changes in ${directory}\n"
-
-    # check if given directory has been updated
-    if git diff --quiet --exit-code -- ./$1/*; then
-        printf "${DONE} No changes to ${directory}\n"
+    # check for changes, then commit (ask to)
+    if ! git diff --exit-code --quiet ./.vscode/*; then
+        printf "$error Changes were made to $code./.vscode/*$clr\n\n"
+        # user preference! uncomment if user input is preferred, leave commented
+        # if you want proceed automatically
+        # proceed
+        printf "$add Tracking changes\n" &&
+            git add ./.vscode/
+        printf "$commit Committing changes\n" &&
+            git commit -m "feat(auto) :robot:  update \`.vscode/\`"
         return
     fi
 
-    printf "${WARNING} Changes in ${directory}\n" &&
-        commit $1
-    return
+    printf "$good No changes made to $code./.vscode/*$clr\n"
+
 }
 
-# generates a changelog based on the commits since the last tag. track and
-# commit changes only if file contents have been modified
+# generate and commit changelog automatically
 function changelog() {
-    changelog="\e[1;34;1;40m./CHANGELOG.md\e[0m"
-    # generate changelog first
-    printf "\n${INFO} Generating changelog\n" &&
+    printf "\n$info Generating $code./CHANGELOG.md$clr\n" &&
         git-cliff --config ./cliff.toml --output ./CHANGELOG.md
 
-    diff "CHANGELOG.md"
-
-    return
+    # check if ./CHANGELOG.md has been updated by git-cliff, by doing this
+    # two useless operation (git add/commit) are avoided (time save).
+    # if it has been updated, then proceed to add and commit the changes
+    printf "$info Checking for changes in $code./CHANGELOG.md$clr\n"
+    if ! git diff --exit-code --quiet ./CHANGELOG.md; then
+        printf "$add Tracking changes\n" &&
+            git add --update --renormalize ./CHANGELOG.md
+        printf "$commit Committing changes\n" &&
+            git commit -m "docs(auto) :robot:  update \`CHANGELOG.md\`"
+        return
+    fi
 }
 
-# generate automatically a changelog
-# generate_changelog() {
-#     printf "\n${INFO} Generating changelog...\n"
-#     git-cliff.exe --output ./CHANGELOG.md
+function main() {
+    # declare read-only variables for icons and colors
+    declare -r overwrite="\e[1A\e[K"
+    declare -r info=" \033[1;34m\033[0m "
+    declare -r good=" \033[1;32m\033[0m "
+    declare -r error=" \033[0;31m\033[0m "
+    declare -r warning=" \033[1;33m\033[0m "
+    declare -r track=" \033[0;34m\033[0m "
+    declare -r commit=" \033[1;35m\033[0m "
+    declare -r clr="\033[0m"
+    declare -r code="\033[1;34;1;40m"
 
-#     # track and commit changes
-#     printf "${ADD} Tracking changes...\n"
-#     git add ./CHANGELOG.md
-
-#     printf "${COMMIT} Committing changes...\n"
-#     git commit -m "docs(changelog) :robot:  update \`./CHANGELOG.md\`"
-
-#     return
-# }
-
-# check if user can push
-
-main() {
-    # # check_diff
-    # diff ".vscode"
-    # generate_changelog
-    # # can_push
-
-    diff ".vscode"
+    # call the fuctions
+    check_vscode
     changelog
 }
 
