refactor(hook): :recycle:  change file structure, generate changelog automatically

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,19 +7,19 @@ INFO=" \033[1;34m\033[0m "
 DONE=" \033[0;32m\033[0m "
 ERROR=" \033[0;31m\033[0m "
 WARNING=" \033[1;33m\033[0m "
-ADDING=" \033[0;34m\033[0m "
-COMMITTING=" \033[1;35m\033[0m "
+ADD=" \033[0;34m\033[0m "
+COMMIT=" \033[1;35m\033[0m "
 
-# get user input to decide whether to push even if file differs
-push_or_stop() {
+# request user input to decide whether to push or not
+get_input() {
     exec </dev/tty # open STDIN to read input
 
     # read user input
     while true; do
-        # `read -p` does not support standard formatting. Use `$"..."`
-        read -p $' \033[1;36m\033[0m  Do you wish to commit and push automatically? (Y/n) ' yn
+        # `read -p` doesn't support standard formatting. Use `$'...'` instead
+        read -p $' \033[1;36m\033[0m  Do you wish to commit and push automagically? (Y/n) ' yn
 
-        # Blank input == allow push
+        # accept blank input as "yes"
         if [ "$yn" = "" ]; then
             yn="Y"
         fi
@@ -27,25 +27,37 @@ push_or_stop() {
         # check input
         case "$yn" in
         [Yy])
-            printf "${ADDING}  Tracking changes\n" &&
-                git add .vscode/*
-
-            printf "${COMMITTING}  Committing changes\n" &&
-                git commit -m "feat(auto) ⚙️  update \`.vscode\`"
-
-            return
+            val=0
             ;;
         [Nn])
-            printf "${ERROR} Exiting\n" # Denying push, throw error
-            exit 126                    # "command not executable"
+            val=1
             ;;
         *)
-            printf "Please answer \"Y\" or \"N\"."
+            printf "Please answer with \"Y\" or \"N\"."
             ;;
         esac
     done
 
     exec <&- # close STDIN
+    return val
+}
+
+track_commmit() {
+    value=get_input
+
+    # check if user wants to track changes
+    if [ $value -eq 0 ]; then
+        printf "${ADD}  Tracking changes...\n"
+        git add ./.vscode/*
+
+        printf "${COMMIT}  Committing changes...\n"
+        git commit -m "feat(vscde) :robot:  update \`./.vscode/*\`"
+
+    elif [ $value -eq 1 ]; then
+        printf "${ERROR} Exiting...\n"
+    fi
+
+    return
 }
 
 # check if files inside .vscode/ have been updated
@@ -57,26 +69,41 @@ check_diff() {
         printf "${DONE} No updates detected!\n"
     else
         printf "${WARNING} Updates detected!\n"
-        push_or_stop
+        track_commmit
     fi
+}
+
+# generate automatically a changelog
+generate_changelog() {
+    printf "\n${INFO} Generating changelog...\n"
+    git-cliff.exe --output ./CHANGELOG.md
+
+    # track and commit changes
+    printf "${ADD} Tracking changes...\n"
+    git add ./CHANGELOG.md
+
+    printf "${COMMIT} Committing changes...\n"
+    git commit -m "docs(changelog) :robot:  update \`./CHANGELOG.md\`"
+
     return
 }
 
-pull_refs() {
-    # pull refs
-    printf "\n${INFO} Pulling refs\n\n" &&
-        git pull origin main &&
-        printf "\n"
-    return
+# check if user can push
+can_push() {
+    # check if user can push
+    # printf "\n${INFO} Checking if you can push...\n"
+
+    if ! [ git push --dry-run --quiet ]; then
+        printf "${ERROR} There is nothing to push!\n"
+        return
+    fi
+
 }
 
 main() {
-    # check if files inside .vscode/ have been updated
     check_diff
-    pull_refs
-    return
+    generate_changelog
+    can_push
 }
 
 main
-
-# exit 1 # throw error to stop hook
